version: '3.8'
services:
  crm-proxy-app:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - crm-api-app-static-data:/vol/static
    ports:
      - "8443:443"
networks:
  default:
    name: crm_development
volumes:
  crm-api-app-static-data:
    external: true
    name: crm-api-app-static-data
